main.datasource.url=jdbc:postgresql://localhost/whiteglovefitness
main.datasource.username=mike
main.datasource.password=cryptoboss

main.liquibase.change-log=com/company/whiteglovefitness/liquibase/changelog.xml

jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=com/company/whiteglovefitness/menu.xml
jmix.ui.composite-menu=true

ui.login.defaultUsername=admin
ui.login.defaultPassword=admin

jmix.core.available-locales=en

jmix.core.default-file-storage=s3
jmix.awsfs.region=${AWS_REGION:us-east-005}
jmix.awsfs.bucket=${AWS_S3_BUCKET:whiteglovefitness}
jmix.awsfs.chunk-size=${AWS_S3_CHUNK_SIZE:8192}
jmix.awsfs.endpoint-url=${AWS_S3_ENDPOINT_URL:https://s3.us-east-005.backblazeb2.com}
jmix.awsfs.use-path-style-bucket-addressing=${AWS_S3_PATH_STYLE_BUCKET_ADDRESSING:false}

# Omit these when using IAM roles or the standard AWS SDK credential provider chain.
jmix.awsfs.access-key=${AWS_ACCESS_KEY_ID:005b41fd009d9350000000002}
jmix.awsfs.secret-access-key=${AWS_SECRET_ACCESS_KEY:K005K9y+H7hSm0CHUJUtGCUi6MCBrfw}

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false

# Enable colors in logs
spring.output.ansi.enabled=always

# 'debug' level logs SQL generated by EclipseLink ORM
logging.level.eclipselink.logging.sql=info

# 'debug' level logs data store operations
logging.level.io.jmix.core.datastore=info

# 'debug' level logs access control constraints
logging.level.io.jmix.core.AccessLogger=debug

# 'debug' level logs all Jmix debug output
logging.level.io.jmix=info

# 'debug' or 'trace' levels help to troubleshoot security problems
logging.level.org.springframework.security=info

logging.level.org.atmosphere=warn

# Maximum allowed size for a single uploaded file
spring.servlet.multipart.max-file-size=10MB

# Maximum allowed size for the entire multi-part request (including form fields)
spring.servlet.multipart.max-request-size=10MB
