spring.config.activate.on-profile=local

main.datasource.url=jdbc:postgresql://localhost/whiteglovefitness
main.datasource.username=mike
main.datasource.password=cryptoboss

ui.login.defaultUsername=${UI_LOGIN_DEFAULT_USERNAME}
ui.login.defaultPassword=${UI_LOGIN_DEFAULT_PASSWORD}

jmix.core.default-file-storage=${JMIX_DEFAULT_FILE_STORAGE}
jmix.awsfs.region=${AWS_REGION}
jmix.awsfs.bucket=${AWS_S3_BUCKET}
jmix.awsfs.chunk-size=${AWS_S3_CHUNK_SIZE:8192}
jmix.awsfs.endpoint-url=${AWS_S3_ENDPOINT_URL}
jmix.awsfs.use-path-style-bucket-addressing=${AWS_S3_PATH_STYLE_BUCKET_ADDRESSING:false}
jmix.awsfs.access-key=${AWS_ACCESS_KEY_ID}
jmix.awsfs.secret-access-key=${AWS_SECRET_ACCESS_KEY}
